version: '3'

services:
  rdb:
    image: postgres
  app:
    build: app
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - "commons.env"
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - rdb
